version: '3.8'

services:
  web:
    image: sunraize/test-php:latest
    container_name: php_container
    ports:
      - "8080:80"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: 'test_zadanie'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql:rw
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
