version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: 'test_zadanie'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./data:/var/lib/mysql:rw
      - ./database:/docker-entrypoint-initdb.d:ro
    networks:
      - app-network

  web:
    image: sunraize/test-php:latest
    container_name: php_container
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
